/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author anis
 */
public class creationFrame extends javax.swing.JFrame {
    
    // not graphicals attributes
    private exercice.Exercice exo;
    private Integer nbQuestion;
    /**
     * Creates new form creatFrame
     */
    public creationFrame() {
        nbQuestion = 1;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tPreambule = new javax.swing.JTextArea();
        tCheminFichierSQL = new javax.swing.JTextField();
        lPreambule = new javax.swing.JLabel();
        lFichierSQL = new javax.swing.JLabel();
        bRecherche = new javax.swing.JButton();
        bValider = new javax.swing.JButton();
        lQuestions = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tQuestion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tReponse = new javax.swing.JTextArea();
        bAjouterQuestion = new javax.swing.JButton();
        lNbQuestions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création d'exercice");
        setName("fenetre"); // NOI18N
        setResizable(false);

        jScrollPane1.setToolTipText("");
        jScrollPane1.setName(""); // NOI18N

        tPreambule.setColumns(20);
        tPreambule.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tPreambule.setRows(5);
        tPreambule.setText("(Préambule...)");
        tPreambule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPreambuleMouseClicked(evt);
            }
        });
        tPreambule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPreambuleKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tPreambule);
        tPreambule.getAccessibleContext().setAccessibleName("");

        tCheminFichierSQL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tCheminFichierSQL.setText("Entrez le chemin du fichier");
        tCheminFichierSQL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCheminFichierSQLFocusGained(evt);
            }
        });

        lPreambule.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lPreambule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPreambule.setText("Préambule :");
        lPreambule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lPreambule.setName("lPreambule"); // NOI18N

        lFichierSQL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lFichierSQL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFichierSQL.setText("Chargement du fichier SQL :");
        lFichierSQL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bRecherche.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        bRecherche.setText("Rechercher");
        bRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRechercheMouseClicked(evt);
            }
        });

        bValider.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        bValider.setText("VALIDER");

        lQuestions.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lQuestions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lQuestions.setText("Questions");
        lQuestions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tQuestion.setColumns(20);
        tQuestion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tQuestion.setRows(5);
        tQuestion.setText("Entrez l'énoncé de la question.");
        tQuestion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tQuestionFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(tQuestion);

        tReponse.setColumns(20);
        tReponse.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tReponse.setRows(5);
        tReponse.setText("Reponse (requête SQL)");
        tReponse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tReponseFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(tReponse);

        bAjouterQuestion.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        bAjouterQuestion.setText("Ajouter question");
        bAjouterQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAjouterQuestionMouseClicked(evt);
            }
        });

        lNbQuestions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNbQuestions.setText("n°1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tCheminFichierSQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                            .addComponent(lPreambule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lFichierSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAjouterQuestion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNbQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPreambule, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lFichierSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCheminFichierSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(lNbQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAjouterQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(bValider, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tCheminFichierSQL.getAccessibleContext().setAccessibleName("tCheminFichierSQL");
        lPreambule.getAccessibleContext().setAccessibleName("");
        lPreambule.getAccessibleContext().setAccessibleDescription("");
        lFichierSQL.getAccessibleContext().setAccessibleName("lFichierSQL");
        bRecherche.getAccessibleContext().setAccessibleName("");
        bValider.getAccessibleContext().setAccessibleName("");
        lQuestions.getAccessibleContext().setAccessibleName("");
        bAjouterQuestion.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("fenetre");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPreambuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPreambuleMouseClicked
        tPreambule.selectAll();
    }//GEN-LAST:event_tPreambuleMouseClicked

    private void tCheminFichierSQLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCheminFichierSQLFocusGained
        tCheminFichierSQL.selectAll();
    }//GEN-LAST:event_tCheminFichierSQLFocusGained

    private void bRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRechercheMouseClicked
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File file = fc.getSelectedFile();
        tCheminFichierSQL.setText(file.getAbsolutePath());
        
    }//GEN-LAST:event_bRechercheMouseClicked

    private void tQuestionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tQuestionFocusGained
        tQuestion.selectAll();
    }//GEN-LAST:event_tQuestionFocusGained

    private void tReponseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tReponseFocusGained
        tReponse.selectAll();
    }//GEN-LAST:event_tReponseFocusGained

    private void bAjouterQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAjouterQuestionMouseClicked
        lNbQuestions.setText("n°"+(++nbQuestion));
    }//GEN-LAST:event_bAjouterQuestionMouseClicked

    private void tPreambuleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPreambuleKeyPressed
    }//GEN-LAST:event_tPreambuleKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjouterQuestion;
    private javax.swing.JButton bRecherche;
    private javax.swing.JButton bValider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lFichierSQL;
    private javax.swing.JLabel lNbQuestions;
    private javax.swing.JLabel lPreambule;
    private javax.swing.JLabel lQuestions;
    private javax.swing.JTextField tCheminFichierSQL;
    private javax.swing.JTextArea tPreambule;
    private javax.swing.JTextArea tQuestion;
    private javax.swing.JTextArea tReponse;
    // End of variables declaration//GEN-END:variables
}
